In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# Plot parameters
plt.style.use('ggplot')
plt.rcParams['axes.facecolor']='w'

%pylab inline
pylab.rcParams['figure.figsize'] = (3, 3)

Populating the interactive namespace from numpy and matplotlib


In [4]:
# Avoid inaccurate floating values (for inverse matrices in dot product for instance)
# See https://stackoverflow.com/questions/24537791/numpy-matrix-inversion-rounding-errors
np.set_printoptions(suppress=True)

# 2.3 Identity and Inverse Matrices

This chapter is light but contain some important definitions. Ths identity matrix or the inverse of a matrix are some concepts that are simple but will be very useful in the next chapters.

# Identity matrices

The identity matrix $\boldsymbol{I}_n$ is a matrix of shape ($n \times n$) that has all 0 except the diagonal filled with 1.

<img src="images/identity.png" width="150" alt="identity">

An identity matrix can be created with the Numpy function `eye()`:

In [5]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

When multiplied with a vector the result is this same vector:

$$\boldsymbol{I}_n\boldsymbol{x} = \boldsymbol{x}$$

### Example 1.

$$
\begin{bmatrix}
    1 & 0 & 0 \\\\
    0 & 1 & 0 \\\\
    0 & 0 & 1
\end{bmatrix}
\times
\begin{bmatrix}
    x_{1} \\\\
    x_{2} \\\\
    x_{3}
\end{bmatrix}=
\begin{bmatrix}
    1 \times x_1 + 0 \times x_2 + 0\times x_3 \\\\
    0 \times x_1 + 1 \times x_2 + 0\times x_3 \\\\
    0 \times x_1 + 0 \times x_2 + 1\times x_3
\end{bmatrix}=
\begin{bmatrix}
    x_{1} \\\\
    x_{2} \\\\
    x_{3}
\end{bmatrix}
$$

In [6]:
x = np.array([[2], [6], [3]])
x

array([[2],
       [6],
       [3]])

In [7]:
xid = np.dot(np.eye(x.shape[0]), x)
xid

array([[ 2.],
       [ 6.],
       [ 3.]])

# Inverse Matrices

The matrix inverse of $\boldsymbol{A}$ is denoted $\boldsymbol{A}^{-1}$ and corresponds to the matrix that results in the identity matrix when it is multiplied by $\boldsymbol{A}$:

$$\boldsymbol{A}^{-1}\boldsymbol{A}=\boldsymbol{I}_n$$

### Example 2.

$$
\boldsymbol{A}=\begin{bmatrix}
    3 & 0 & 2 \\\\
    2 & 0 & -2 \\\\
    0 & 1 & 1
\end{bmatrix}
$$

For this example, we will use the Numpy function `linalg.inv()` to calculate the inverse of $\boldsymbol{A}$. Let's start by creating $\boldsymbol{A}$:

In [8]:
A = np.array([[3, 0, 2], [2, 0, -2], [0, 1, 1]])
A

array([[ 3,  0,  2],
       [ 2,  0, -2],
       [ 0,  1,  1]])

Now we calculate its inverse:

In [9]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.2,  0.2,  0. ],
       [-0.2,  0.3,  1. ],
       [ 0.2, -0.3, -0. ]])

We can check that $\boldsymbol{A\_inv}$ is well the inverse of $\boldsymbol{A}$:

$$
\begin{align*}
\boldsymbol{A}^{-1}\boldsymbol{A} &=
\begin{bmatrix}
    3 & 0 & 2 \\\\
    2 & 0 & -2 \\\\
    0 & 1 & 1
\end{bmatrix} \times
\begin{bmatrix}
    0.2 & 0.2 & 0 \\\\
    -0.2 & 0.3 & 1 \\\\
    0.2 & -0.3 & 0
\end{bmatrix}\\\\
&= \begin{bmatrix}
    3\times0.2 + 0\times-0.2 + 2\times0.2 & 3\times0.2 + 0\times0.3 + 2\times-0.3  & 3\times0 + 0\times1 + 2\times0  \\\\
    2\times0.2 + 0\times-0.2 + -2\times0.2 & 2\times0.2 + 0\times0.3 + -2\times-0.3  & 2\times0 + 0\times1 + -2\times0  \\\\
    0\times0.2 + 1\times-0.2 + 1\times0.2 & 0\times0.2 + 1\times0.3 + 1\times-0.3  & 0\times0 + 1\times1 + 1\times0
\end{bmatrix}\\\\
&= \begin{bmatrix}
    1 & 0 & 0 \\\\
    0 & 1 & 0 \\\\
    0 & 0 & 1
\end{bmatrix}
\end{align*}
$$

It works! Let's check the result with Python:

In [10]:
A_bis = np.dot(A_inv, A)
A_bis

array([[ 1.,  0., -0.],
       [ 0.,  1., -0.],
       [ 0.,  0.,  1.]])

We will see that inverse of matrices can be very usefull. For example, to solve set of linear equations. We must note however that non square matrices (that is matrix with more columns than rows or more rows than columns) don't have inverse.

# Sovling a system of linear equations

Some details about set of linear equations can be found [in 2.2]().

The inverse matrix can be used to solve the equation $\boldsymbol{Ax}=\boldsymbol{b}$ by adding it to each term:

$$\boldsymbol{A}^{-1}\boldsymbol{Ax}=\boldsymbol{A}^{-1}\boldsymbol{b}$$

Since we know by definition of the inverse that $\boldsymbol{A}^{-1}\boldsymbol{A}=\boldsymbol{I}$, we can simplify

$$\boldsymbol{I}_n\boldsymbol{x}=\boldsymbol{A}^{-1}\boldsymbol{b}$$

We saw that a vector is not changed when multiplied by the identity matrix. So we can write:

$$\boldsymbol{x}=\boldsymbol{A}^{-1}\boldsymbol{b}$$

This introduces different cases according to the linear system because $\boldsymbol{A}^{-1}$ exists only if the equation $\boldsymbol{Ax}=\boldsymbol{b}$ has one and only one solution. [The next chapter]() is almost all about systems of linear equations and number of solutions.

# Singular matrices

Some matrices are not invertible. They are called **singular**.