In [2]:
import numpy as np
import matplotlib.pyplot as plt

/Users/lsp/.virtualenvs/kaggle/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')


In [19]:
# Plot parameters
plt.style.use('ggplot')
plt.rcParams['axes.facecolor']='w'

%pylab inline
pylab.rcParams['figure.figsize'] = (3, 3)

Populating the interactive namespace from numpy and matplotlib


In [136]:
# Avoid inaccurate floating values (for inverse matrices in dot product for instance)
# See https://stackoverflow.com/questions/24537791/numpy-matrix-inversion-rounding-errors
np.set_printoptions(suppress=True)

# 2.1 Scalars, Vectors, Matrices and Tensors

- A scalar is a single number
- A vector is an array of numbers. Geometrically, each value can be thought of a different axis.

$
\boldsymbol{x} =\begin{bmatrix}
    x_1 \\\\
    x_2 \\\\
    \cdots \\\\
    x_n
\end{bmatrix}
$

- A matrix is a 2-D array

$$
\boldsymbol{A}=
\begin{bmatrix}
    A_{1,1} & A_{1,2} & \cdots & A_{1,n} \\\\
    A_{2,1} & A_{2,2} & \cdots & A_{2,n} \\\\
    \cdots & \cdots & \cdots & \cdots \\\\
    A_{m,1} & A_{m,2} & \cdots & A_{m,n}
\end{bmatrix}
$$

- A tensor is a n-D array with n>2

In [5]:
# Create a vector
x = np.array([1, 2, 3, 4])
print(x)

[1 2 3 4]


In [35]:
# Create a (3x2) matrix (nested brackets)
A = np.array([[1, 2], [3, 4], [5, 6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


#### The shape (number of rows x number of columns) of a numpy matrix can be get with

In [36]:
A.shape

(3, 2)

In [37]:
print("A has %s rows and %s columns" %(A.shape[0], A.shape[1]))

A has 3 rows and 2 columns


### Transpose

The transpose $A^{\text{T}}$ of the matrix A corresponds to the mirrored axes.

$$
\boldsymbol{A}=
\begin{bmatrix}
    A_{1,1} & A_{1,2} \\\\
    A_{2,1} & A_{2,2} \\\\
    A_{3,1} & A_{3,2}
\end{bmatrix}
$$

$$
\boldsymbol{A}^{\text{T}}=
\begin{bmatrix}
    A_{1,1} & A_{2,1} & A_{3,1} \\\\
    A_{1,2} & A_{2,2} & A_{3,2} \\\\
\end{bmatrix}
$$

The shape ($m \times n$) is inverted and becomes ($n \times m$).

In [73]:
# Create a matrix A and transpose it
A = np.array([[1, 2], [3, 4], [5, 6]])
print("A.shape: %s\n\n%s" %(A.shape, A))

A.shape: (3, 2)

[[1 2]
 [3 4]
 [5 6]]


In [74]:
A_t = A.T
print("A_t.shape: %s\n\n%s" %(A_t.shape, A_t))

A_t.shape: (2, 3)

[[1 3 5]
 [2 4 6]]


In [39]:
print("The shape of A is %s. The shape of the transpose of A is %s" %(A.shape, A_t.shape))

The shape of A is (3, 2). The shape of the transpose of A is (2, 3)


### Addition

Matrices can be added if they have the same shape

$$
\begin{bmatrix}
    A_{1,1} & A_{1,2} \\\\
    A_{2,1} & A_{2,2} \\\\
    A_{3,1} & A_{3,2}
\end{bmatrix}+
\begin{bmatrix}
    B_{1,1} & B_{1,2} \\\\
    B_{2,1} & B_{2,2} \\\\
    B_{3,1} & B_{3,2}
\end{bmatrix}=
\begin{bmatrix}
    A_{1,1} + B_{1,1} & A_{1,2} + B_{1,2} \\\\
    A_{2,1} + B_{2,1} & A_{2,2} + B_{2,2} \\\\
    A_{3,1} + B_{3,1} & A_{3,2} + B_{3,2}
\end{bmatrix}
$$

$$\boldsymbol{A}_{i,j} + \boldsymbol{B}_{i,j} = \boldsymbol{C}_{i,j}$$

In [72]:
A = np.array([[1, 2], [3, 4], [5, 6]])
print("A.shape: %s\n\n%s" %(A.shape, A))

A.shape: (3, 2)

[[1 2]
 [3 4]
 [5 6]]


In [71]:
B = np.array([[2, 5], [7, 4], [4, 3]])
print("B.shape: %s\n\n%s" %(B.shape, B))

B.shape: (3, 2)

[[2 5]
 [7 4]
 [4 3]]


In [44]:
# Add matrices A and B
C = A + B
print("C.shape: %s\n\n%s" %(C.shape, C))

[[ 3  7]
 [10  8]
 [ 9  9]]


#### The shape of C is the same as the shape of A and B.

In [52]:
print("A: %s\nB: %s\nC: %s" %(A.shape, B.shape, C.shape))

A: (3, 2)
B: (3, 2)
C: (3, 2)


It is also possible to add a scalar to a matrix

$$
\alpha+ \begin{bmatrix}
    A_{1,1} & A_{1,2} \\\\
    A_{2,1} & A_{2,2} \\\\
    A_{3,1} & A_{3,2}
\end{bmatrix}=
\begin{bmatrix}
    \alpha + A_{1,1} & \alpha + A_{1,2} \\\\
    \alpha + A_{2,1} & \alpha + A_{2,2} \\\\
    \alpha + A_{3,1} & \alpha + A_{3,2}
\end{bmatrix}
$$

In [70]:
# Add 4 to the matrix A
C = 4*A
print("C.shape: %s\n\n%s" %(C.shape, C))

C.shape: (3, 2)

[[ 4  8]
 [12 16]
 [20 24]]


### Broadcasting

$$
\begin{bmatrix}
    A_{1,1} & A_{1,2} \\\\
    A_{2,1} & A_{2,2} \\\\
    A_{3,1} & A_{3,2}
\end{bmatrix}+
\begin{bmatrix}
    B_{1,1} \\\\
    B_{2,1} \\\\
    B_{3,1}
\end{bmatrix}=
\begin{bmatrix}
    A_{1,1} + B_{1,1} & A_{1,2} + B_{1,1} \\\\
    A_{2,1} + B_{2,1} & A_{2,2} + B_{2,1} \\\\
    A_{3,1} + B_{3,1} & A_{3,2} + B_{3,1}
\end{bmatrix}
$$

is equivalent to

$$
\begin{bmatrix}
    A_{1,1} & A_{1,2} \\\\
    A_{2,1} & A_{2,2} \\\\
    A_{3,1} & A_{3,2}
\end{bmatrix}+
\begin{bmatrix}
    B_{1,1} & B_{1,1} \\\\
    B_{2,1} & B_{2,1} \\\\
    B_{3,1} & B_{3,1}
\end{bmatrix}=
\begin{bmatrix}
    A_{1,1} + B_{1,1} & A_{1,2} + B_{1,1} \\\\
    A_{2,1} + B_{2,1} & A_{2,2} + B_{2,1} \\\\
    A_{3,1} + B_{3,1} & A_{3,2} + B_{3,1}
\end{bmatrix}
$$

where the ($3 \times 1$) matrix is converted to the right shape ($3 \times 2$) by copying the first column. Numpy will do that automatically if the shapes can match.

In [67]:
A = np.array([[1, 2], [3, 4], [5, 6]])
print("A.shape: %s\n\n%s" %(A.shape, A))

A.shape: (3, 2)

[[1 2]
 [3 4]
 [5 6]]


In [68]:
B = np.array([[2], [4], [6]])
print("B.shape: %s\n\n%s" %(B.shape, B))

B.shape: (3, 1)

[[2]
 [4]
 [6]]


In [69]:
# Broadcasting
C=A+B
print("C.shape: %s\n\n%s" %(C.shape, C))

C.shape: (3, 2)

[[ 3  4]
 [ 7  8]
 [11 12]]
