In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Plot parameters
plt.style.use('ggplot')
plt.rcParams['axes.facecolor']='w'

%pylab inline
pylab.rcParams['figure.figsize'] = (3, 3)

Populating the interactive namespace from numpy and matplotlib


In [3]:
# Avoid inaccurate floating values (for inverse matrices in dot product for instance)
# See https://stackoverflow.com/questions/24537791/numpy-matrix-inversion-rounding-errors
np.set_printoptions(suppress=True)

# 2.2 Multiplying Matrices and Vectors

The matrix product is the sum of the rows of the first matrix and the columns of the second one. Thus, if the shape of the first matrix is ($m \times n$) the second matrix need to be of shape ($n \times x$).

### Example 1. $\boldsymbol{A} _{3,2} \times \boldsymbol{B} _{2, 1} = \boldsymbol{C} _{3, 1}$

$$
\begin{bmatrix}
    A_{1,1} & A_{1,2} \\\\
    A_{2,1} & A_{2,2} \\\\
    A_{3,1} & A_{3,2}
\end{bmatrix}\times
\begin{bmatrix}
    B_{1,1} \\\\
    B_{2,1}
\end{bmatrix}=
\begin{bmatrix}
    A_{1,1} \times B_{1,1} + A_{1,2} \times B_{2,1} \\\\
    A_{2,1} \times B_{1,1} + A_{2,2} \times B_{2,1} \\\\
    A_{3,1} \times B_{1,1} + A_{3,2} \times B_{2,1}
\end{bmatrix}
$$

In [4]:
A = np.array([[1, 2], [3, 4], [5, 6]])
print("A.shape: %s\n\n%s" %(A.shape, A))

A.shape: (3, 2)

[[1 2]
 [3 4]
 [5 6]]


In [5]:
B = np.array([[2], [4]])
print("B.shape: %s\n\n%s" %(B.shape, B))

B.shape: (2, 1)

[[2]
 [4]]


#### The numpy command 'dot' can be used to compute the matrix (or dot) product

In [6]:
C = np.dot(A, B)
print("C.shape: %s\n\n%s" %(C.shape, C))

C.shape: (3, 1)

[[10]
 [22]
 [34]]


### Example 2. $\boldsymbol{A} _{4,3} \times \boldsymbol{B} _{3, 2} = \boldsymbol{C} _{4, 2}$

$$
\begin{bmatrix}
    A_{1,1} & A_{1,2} & A_{1,3} \\\\
    A_{2,1} & A_{2,2} & A_{2,3} \\\\
    A_{3,1} & A_{3,2} & A_{3,3} \\\\
    A_{4,1} & A_{4,2} & A_{4,3}
\end{bmatrix}\times
\begin{bmatrix}
    B_{1,1} & B_{1,2} \\\\
    B_{2,1} & B_{2,2} \\\\
    B_{3,1} & B_{3,2}
\end{bmatrix}=
\begin{bmatrix}
    A_{1,1} \times B_{1,1} + A_{1,2} \times B_{2,1} + A_{1,3} \times B_{3,1} & A_{1,1} \times B_{1,2} + A_{1,2} \times B_{2,2} + A_{1,3} \times B_{3,2} \\\\
    A_{2,1} \times B_{1,1} + A_{2,2} \times B_{2,1} + A_{2,3} \times B_{3,1} & A_{2,1} \times B_{1,2} + A_{2,2} \times B_{2,2} + A_{2,3} \times B_{3,2} \\\\
    A_{3,1} \times B_{1,1} + A_{3,2} \times B_{2,1} + A_{3,3} \times B_{3,1} & A_{3,1} \times B_{1,2} + A_{3,2} \times B_{2,2} + A_{3,3} \times B_{3,2} \\\\
    A_{4,1} \times B_{1,1} + A_{4,2} \times B_{2,1} + A_{4,3} \times B_{3,1} & A_{4,1} \times B_{1,2} + A_{4,2} \times B_{2,2} + A_{4,3} \times B_{3,2} \\\\
\end{bmatrix}
$$

In [7]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print("A.shape: %s\n\n%s" %(A.shape, A))

A.shape: (4, 3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [8]:
B = np.array([[2, 7], [1, 2], [3, 6]])
print("B.shape: %s\n\n%s" %(B.shape, B))

B.shape: (3, 2)

[[2 7]
 [1 2]
 [3 6]]


In [9]:
C = np.dot(A, B)
print("C.shape: %s\n\n%s" %(C.shape, C))

C.shape: (4, 2)

[[ 13  29]
 [ 31  74]
 [ 49 119]
 [ 67 164]]


#### So the dot product can be formalized like that:

$$
C_{i,j} = A_{i,k}B_{k,j} = \sum\limits_{k}A_{i,k}B_{k,i}
$$

More detailed examples about the dot product can be found [here](https://www.mathsisfun.com/algebra/matrix-multiplying.html).

## Matrices mutliplication is distributive

$\boldsymbol{A}(\boldsymbol{B}+\boldsymbol{C}) = \boldsymbol{AB}+\boldsymbol{AC}$

#### Example 1.

$
\boldsymbol{A}=\begin{bmatrix}
    2 & 3 \\\\
    1 & 4 \\\\
    7 & 6
\end{bmatrix}, 
\boldsymbol{B}=\begin{bmatrix}
    5 \\\\
    2
\end{bmatrix}, 
\boldsymbol{C}=\begin{bmatrix}
    4 \\\\
    3
\end{bmatrix}
$


$
\boldsymbol{A}(\boldsymbol{B}+\boldsymbol{C})=\begin{bmatrix}
    2 & 3 \\\\
    1 & 4 \\\\
    7 & 6
\end{bmatrix}\times
\left(\begin{bmatrix}
    5 \\\\
    2
\end{bmatrix}+
\begin{bmatrix}
    4 \\\\
    3
\end{bmatrix}\right)=
\begin{bmatrix}
    2 & 3 \\\\
    1 & 4 \\\\
    7 & 6
\end{bmatrix}\times
\begin{bmatrix}
    9 \\\\
    5
\end{bmatrix}=
\begin{bmatrix}
    2 \times 9 + 3 \times 5 \\\\
    1 \times 9 + 4 \times 5 \\\\
    7 \times 9 + 6 \times 5
\end{bmatrix}=
\begin{bmatrix}
    33 \\\\
    29 \\\\
    93
\end{bmatrix}
$

is equivalent to

$
\boldsymbol{A}\boldsymbol{B}+\boldsymbol{A}\boldsymbol{C} = \begin{bmatrix}
    2 & 3 \\\\
    1 & 4 \\\\
    7 & 6
\end{bmatrix}\times
\begin{bmatrix}
    5 \\\\
    2
\end{bmatrix}+
\begin{bmatrix}
    2 & 3 \\\\
    1 & 4 \\\\
    7 & 6
\end{bmatrix}\times
\begin{bmatrix}
    4 \\\\
    3
\end{bmatrix}=
\begin{bmatrix}
    2 \times 5 + 3 \times 2 \\\\
    1 \times 5 + 4 \times 2 \\\\
    7 \times 5 + 6 \times 2
\end{bmatrix}+
\begin{bmatrix}
    2 \times 4 + 3 \times 3 \\\\
    1 \times 4 + 4 \times 3 \\\\
    7 \times 4 + 6 \times 3
\end{bmatrix}=
\begin{bmatrix}
    16 \\\\
    13 \\\\
    47
\end{bmatrix}+
\begin{bmatrix}
    17 \\\\
    16 \\\\
    46
\end{bmatrix}=
\begin{bmatrix}
    33 \\\\
    29 \\\\
    93
\end{bmatrix}
$

In [10]:
A = np.array([[2, 3], [1, 4], [7, 6]])
print("A.shape: %s\n\n%s" %(A.shape, A))
B = np.array([[5], [2]])
print("\nB.shape: %s\n\n%s" %(B.shape, B))

A.shape: (3, 2)

[[2 3]
 [1 4]
 [7 6]]

B.shape: (2, 1)

[[5]
 [2]]


In [11]:
C = np.array([[4], [3]])
print("C.shape: %s\n\n%s" %(C.shape, C))

C.shape: (2, 1)

[[4]
 [3]]


In [12]:
# A(B + C)
D = np.dot(A, (B+C))
print("D.shape: %s\n\n%s" %(D.shape, D))

D.shape: (3, 1)

[[33]
 [29]
 [93]]


In [13]:
# AB + AC
D = np.dot(A, B) + np.dot(A, C)
print("D.shape: %s\n\n%s" %(D.shape, D))

D.shape: (3, 1)

[[33]
 [29]
 [93]]


## Matrices mutliplication is associative

$\boldsymbol{A}(\boldsymbol{BC}) = \boldsymbol{AB}(\boldsymbol{C})$


In [14]:
A = np.array([[2, 3], [1, 4], [7, 6]])
print("A.shape: %s\n\n%s" %(A.shape, A))
B = np.array([[5, 3], [2, 2]])
print("\nB.shape: %s\n\n%s" %(B.shape, B))

A.shape: (3, 2)

[[2 3]
 [1 4]
 [7 6]]

B.shape: (2, 2)

[[5 3]
 [2 2]]


In [15]:
# A(BC)
D = np.dot(A, np.dot(B, C))
print("D.shape: %s\n\n%s" %(D.shape, D))

D.shape: (3, 1)

[[100]
 [ 85]
 [287]]


In [16]:
# AB(C)
D = np.dot(np.dot(A, B), C)
print("D.shape: %s\n\n%s" %(D.shape, D))

D.shape: (3, 1)

[[100]
 [ 85]
 [287]]


## Matrix multiplication is not commutative

$\boldsymbol{AB} \neq \boldsymbol{BA}$

In [17]:
A = np.array([[2, 3], [6, 5]])
print("\nA.shape: %s\n\n%s" %(A.shape, A))

B = np.array([[5, 3], [2, 2]])
print("\nB.shape: %s\n\n%s" %(B.shape, B))


A.shape: (2, 2)

[[2 3]
 [6 5]]

B.shape: (2, 2)

[[5 3]
 [2 2]]


In [18]:
AB = np.dot(A, B)
print("AB.shape: %s\n\n%s" %(AB.shape, AB))

AB.shape: (2, 2)

[[16 12]
 [40 28]]


In [19]:
BA = np.dot(B, A)
print("BA.shape: %s\n\n%s" %(BA.shape, BA))

BA.shape: (2, 2)

[[28 30]
 [16 16]]


### However vector multiplication is commutative

$x^{ \text{T}}y = y^{\text{T}}x $

In [20]:
x = np.array([[2], [6]])
print("\nx.shape: %s\n\n%s" %(x.shape, x))

y = np.array([[5], [2]])
print("\ny.shape: %s\n\n%s" %(y.shape, y))


x.shape: (2, 1)

[[2]
 [6]]

y.shape: (2, 1)

[[5]
 [2]]


In [21]:
x_ty = np.dot(x.T, y)
print("x_ty.shape: %s\n\n%s" %(x_ty.shape, x_ty))

x_ty.shape: (1, 1)

[[22]]


In [22]:
y_tx = np.dot(y.T, x)
print("y_tx.shape: %s\n\n%s" %(y_tx.shape, y_tx))

y_tx.shape: (1, 1)

[[22]]


### Simplification of the matrix product

$(AB)^{\text{T}} = B^{\text{T}}A^{\text{T}}$

In [23]:
A = np.array([[2, 3], [1, 4], [7, 6]])
print("A.shape: %s\n\n%s" %(A.shape, A))
B = np.array([[5, 3], [2, 2]])
print("\nB.shape: %s\n\n%s" %(B.shape, B))

A.shape: (3, 2)

[[2 3]
 [1 4]
 [7 6]]

B.shape: (2, 2)

[[5 3]
 [2 2]]


$(AB)^{\text{T}}$:

In [24]:
AB_t = np.dot(A, B).T
print("AB_t.shape: %s\n\n%s" %(AB_t.shape, AB_t))

AB_t.shape: (2, 3)

[[16 13 47]
 [12 11 33]]


$B^{\text{T}}A^{\text{T}}$:

In [25]:
B_tA = np.dot(B.T, A.T)
print("B_tA.shape: %s\n\n%s" %(B_tA.shape, B_tA))

B_tA.shape: (2, 3)

[[16 13 47]
 [12 11 33]]
