In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Plot parameters
plt.style.use('ggplot')
plt.rcParams['axes.facecolor']='w'

%pylab inline
pylab.rcParams['figure.figsize'] = (3, 3)

Populating the interactive namespace from numpy and matplotlib


In [3]:
# Avoid inaccurate floating values (for inverse matrices in dot product for instance)
# See https://stackoverflow.com/questions/24537791/numpy-matrix-inversion-rounding-errors
np.set_printoptions(suppress=True)

# 2.3 Identity and Inverse Matrices

# Identity matrices

The identity matrix $\boldsymbol{I}_n$ is a matrix of shape ($n \times n$) that has all 0 except the diagonal filled with 1.

$
\boldsymbol{I}_3=
\begin{bmatrix}
    1 & 0 & 0 \\\\
    0 & 1 & 0 \\\\
    0 & 0 & 1 \\\\
\end{bmatrix}
$

An identity matrix can be created with the numpy command 'eye':

In [4]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

When multiplied with a vector the result is this same vector:

$\boldsymbol{I}_n\boldsymbol{x} = \boldsymbol{x}$

### Example 1.

$
\begin{bmatrix}
    1 & 0 & 0 \\\\
    0 & 1 & 0 \\\\
    0 & 0 & 1 \\\\
\end{bmatrix}
\times
\begin{bmatrix}
    x_{1} \\\\
    x_{2} \\\\
    x_{3}
\end{bmatrix}=
\begin{bmatrix}
    1 \times x_1 + 0 \times x_2 + 0\times x_3 \\\\
    0 \times x_1 + 1 \times x_2 + 0\times x_3 \\\\
    0 \times x_1 + 0 \times x_2 + 1\times x_3 \\\\
\end{bmatrix}=
\begin{bmatrix}
    x_{1} \\\\
    x_{2} \\\\
    x_{3}
\end{bmatrix}
$

In [5]:
x = np.array([[2], [6], [3]])
print("\nx.shape: %s\n\n%s" %(x.shape, x))

xid = np.dot(np.eye(x.shape[0]), x)
print("\nxid.shape: %s\n\n%s" %(xid.shape, xid))


x.shape: (3, 1)

[[2]
 [6]
 [3]]

xid.shape: (3, 1)

[[ 2.]
 [ 6.]
 [ 3.]]


# Inverse Matrices

The matrix inverse of $\boldsymbol{A}$ is denoted $\boldsymbol{A}^{-1}$ and correspond to the matrix that result in the identity matrix when it is multiplied by $\boldsymbol{A}$:

$\boldsymbol{A}^{-1}\boldsymbol{A}=\boldsymbol{I}_n$

### Example 2.

In [6]:
A = np.array([[3, 0, 2], [2, 0, -2], [0, 1, 1]])
print("\nA.shape: %s\n\n%s" %(A.shape, A))

A_inv = np.linalg.inv(A)
print("\nA_inv.shape: %s\n\n%s" %(A_inv.shape, A_inv))


A.shape: (3, 3)

[[ 3  0  2]
 [ 2  0 -2]
 [ 0  1  1]]

A_inv.shape: (3, 3)

[[ 0.2  0.2  0. ]
 [-0.2  0.3  1. ]
 [ 0.2 -0.3 -0. ]]


We can check that $\boldsymbol{A\_inv}$ is well the inverse of $\boldsymbol{A}$:

$
\begin{align*}
\boldsymbol{A}^{-1}\boldsymbol{A} &=
\begin{bmatrix}
    3 & 0 & 2 \\\\
    2 & 0 & -2 \\\\
    0 & 1 & 1 \\\\
\end{bmatrix} \times
\begin{bmatrix}
    0.2 & 0.2 & 0 \\\\
    -0.2 & 0.3 & 1 \\\\
    0.2 & -0.3 & 0 \\\\
\end{bmatrix}\\\\
&= \begin{bmatrix}
    3\times0.2 + 0\times-0.2 + 2\times0.2 & 3\times0.2 + 0\times0.3 + 2\times-0.3  & 3\times0 + 0\times1 + 2\times0  \\\\
    2\times0.2 + 0\times-0.2 + -2\times0.2 & 2\times0.2 + 0\times0.3 + -2\times-0.3  & 2\times0 + 0\times1 + -2\times0  \\\\
    0\times0.2 + 1\times-0.2 + 1\times0.2 & 0\times0.2 + 1\times0.3 + 1\times-0.3  & 0\times0 + 1\times1 + 1\times0  \\\\
\end{bmatrix}\\\\
&= \begin{bmatrix}
    1 & 0 & 0 \\\\
    0 & 1 & 0 \\\\
    0 & 0 & 1 \\\\
\end{bmatrix}
\end{align*}
$

In [7]:
A_bis = np.dot(A_inv, A)
print("\nA_bis.shape: %s\n\n%s" %(A_bis.shape, A_bis))


A_bis.shape: (3, 3)

[[ 1.  0. -0.]
 [ 0.  1. -0.]
 [ 0.  0.  1.]]


# Sovling the system of linear equations

The inverse matrix can be used to solve the equation $\boldsymbol{Ax}=\boldsymbol{b}$ by adding it to each term:

$\boldsymbol{A}^{-1}\boldsymbol{Ax}=\boldsymbol{A}^{-1}\boldsymbol{b}$

$\boldsymbol{I}_n\boldsymbol{x}=\boldsymbol{A}^{-1}\boldsymbol{b}$

$\boldsymbol{x}=\boldsymbol{A}^{-1}\boldsymbol{b}$

This introduces different cases according to the linear system because $\boldsymbol{A}^{-1}$ exists only if the equation $\boldsymbol{Ax}=\boldsymbol{b}$ has one and only one solution.

# Singular matrices

Some matrices are not invertible. They are called **singular**.