In [2]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# Plot parameters
sns.set()
# Seven hls color palette
current_palette_7 = sns.color_palette("hls", 7)
sns.set_palette(current_palette_7)

%pylab inline
pylab.rcParams['figure.figsize'] = (4, 4)
plt.rcParams['xtick.major.size'] = 0
plt.rcParams['ytick.major.size'] = 0
# rcParams.keys()

Populating the interactive namespace from numpy and matplotlib


In [4]:
# Avoid inaccurate floating values (for inverse matrices in dot product for instance)
# See https://stackoverflow.com/questions/24537791/numpy-matrix-inversion-rounding-errors
np.set_printoptions(suppress=True)

# Singular Value Decomposition

The eigendecomposition can be done only for square matrices. The way to decompose other type of matrices that can't be done with eigendecomposition is to use singular value decomposition. Instead of having the eigendecomposition equation:

$$
\boldsymbol{A}=\boldsymbol{V}\cdot diag(\boldsymbol{\lambda}) \cdot \boldsymbol{V}^{-1}
$$

We decompose it into 3 matrices:

$$
\boldsymbol{A}=\boldsymbol{UDV}^{\text{T}}
$$

With $\boldsymbol{U}$ and $\boldsymbol{V}$ being orthogonal matrices ($\boldsymbol{U}^\text{T}=\boldsymbol{U}^{-1}$ and $\boldsymbol{V}^\text{T}=\boldsymbol{V}^{-1}$) and $\boldsymbol{D}$ being a diagonal matrix (all 0 except the diagonal). However $\boldsymbol{D}$ is not necessarily square.

The columns of $\boldsymbol{U}$ are the left-singular vectors of $\boldsymbol{A}$ while the columns of $\boldsymbol{V}$ are the right-singular vectors of $\boldsymbol{A}$. The values along the diagonal of $\boldsymbol{D}$ are the singular values of $\boldsymbol{A}$.

Before continuing let's take an example of a non square matrix:

$
A=\begin{bmatrix}
    7 & 2\\\\
    3 & 4\\\\
    5 & 3
\end{bmatrix}
$

The singular value decomposition can be done with the `linalg.svd` function from Numpy. Note that `np.linalg.eig(A)` works only on square matrices and will give an error for `A`:

In [4]:
A = np.array([[7, 2], [3, 4], [5, 3]])
print 'A:\n', A
print 'np.linalg.eig(A):', np.linalg.eig(A)

A:
[[7 2]
 [3 4]
 [5 3]]
np.linalg.eig(A):

LinAlgError: Last 2 dimensions of the array must be square

## The left-singular values

The left-singular values of $\boldsymbol{A}$ correspond to the eigenvectors of $\boldsymbol{AA}^\text{T}$.

### Example 1.

Note that the sign difference comes from the fact that eigenvectors are not unique. The `linalg` functions from Numpy return the normalized eigenvectors. Scaling by `-1` doesn't change their direction or the fact that they are unit vectors.

In [6]:
U, S, V = np.linalg.svd(A)
D = np.diag(S)
print '\nLeft singular vectors of A:\n', U

print '\nEigenvectors of AA_transpose:\n', np.linalg.eig(A.dot(A.T))[1]


Left singular vectors of A:
[[-0.69366543  0.59343205 -0.40824829]
 [-0.4427092  -0.79833696 -0.40824829]
 [-0.56818732 -0.10245245  0.81649658]]

Eigenvectors of AA_transpose:
[[-0.69366543 -0.59343205 -0.40824829]
 [-0.4427092   0.79833696 -0.40824829]
 [-0.56818732  0.10245245  0.81649658]]


## The right-singular values

The right-singular values of $\boldsymbol{A}$ correspond to the eigenvectors of $\boldsymbol{A}^\text{T}\boldsymbol{A}$.

### Example 2.

In [7]:
U, S, V = np.linalg.svd(A)
print '\nRight singular vectors of A:\n', V

print '\nEigenvectors of A_transposeA:\n', np.linalg.eig(A.T.dot(A))[1]


Right singular vectors of A:
[[-0.88033817 -0.47434662]
 [ 0.47434662 -0.88033817]]

Eigenvectors of A_transposeA:
[[ 0.88033817 -0.47434662]
 [ 0.47434662  0.88033817]]


## The nonzero singular values

The nonzero singular values of $\boldsymbol{A}$ are the square roots of the eigenvalues of $\boldsymbol{A}^\text{T}\boldsymbol{A}$ and $\boldsymbol{AA}^\text{T}$.

### Example 3.

In [36]:
U, S, V = np.linalg.svd(A)
print '\nSingular values of A:\n', S

print '\nEigenvalues of A_transposeA:\n', np.linalg.eig(A.T.dot(A))[0]
print '\nEigenvalues of AA_transpose:\n', np.linalg.eig(A.dot(A.T))[0]
print '\nSquare root of the eigenvalues:\n', np.sqrt(np.linalg.eig(A.T.dot(A))[0])


Singular values of A:
[ 10.25142677   2.62835484]

Eigenvalues of A_transposeA:
[ 105.09175083    6.90824917]

Eigenvalues of AA_transpose:
[ 105.09175083    6.90824917   -0.        ]

Square root of the eigenvalues:
[ 10.25142677   2.62835484]


# References

[1] [C.O.S. Sorzano from Universidad San Pablo](http://biocomp.cnb.csic.es/~coss/Docencia/algebra/tema8.pdf)