In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Plot parameters
plt.style.use('ggplot')
plt.rcParams['axes.facecolor']='w'

%pylab inline
pylab.rcParams['figure.figsize'] = (3, 3)

Populating the interactive namespace from numpy and matplotlib


In [3]:
# Avoid inaccurate floating values (for inverse matrices in dot product for instance)
# See https://stackoverflow.com/questions/24537791/numpy-matrix-inversion-rounding-errors
np.set_printoptions(suppress=True)

# 2.2 Multiplying Matrices and Vectors

The standard way to multiply matrices is not to multiply each element of one with each elements of the other (this is the element-wise product). The matrix product, also called dot product, is the sum of the rows of the first matrix times the columns of the second matrix or the vector. This implies that the number of columns of the first matrix must be equals to the number of rows of the second matrix. Thus, if the shape of the first matrix is ($m \times n$) the second matrix need to be of shape ($n \times x$).

![dotProduct](images/dotProduct.png)

### Example 1.

Multiplication of a matrix and a vector.

$\boldsymbol{A} _{3,2} \times \boldsymbol{B} _{2, 1} = \boldsymbol{C} _{3, 1}$

$
\begin{bmatrix}
    A_{1,1} & A_{1,2} \\\\
    A_{2,1} & A_{2,2} \\\\
    A_{3,1} & A_{3,2}
\end{bmatrix}\times
\begin{bmatrix}
    B_{1,1} \\\\
    B_{2,1}
\end{bmatrix}=
\begin{bmatrix}
    A_{1,1} \times B_{1,1} + A_{1,2} \times B_{2,1} \\\\
    A_{2,1} \times B_{1,1} + A_{2,2} \times B_{2,1} \\\\
    A_{3,1} \times B_{1,1} + A_{3,2} \times B_{2,1}
\end{bmatrix}
$

For instance

$
\begin{bmatrix}
    1 & 2 \\\\
    3 & 4 \\\\
    5 & 6
\end{bmatrix}\times
\begin{bmatrix}
    2 \\\\
    4
\end{bmatrix}=
\begin{bmatrix}
    1 \times 2 + 2 \times 4 \\\\
    3 \times 2 + 4 \times 4 \\\\
    5 \times 2 + 6 \times 4
\end{bmatrix}
=
\begin{bmatrix}
    10 \\\\
    22 \\\\
    34
\end{bmatrix}
$

#### The Numpy command 'dot' can be used to compute the matrix product (or dot product)

Let's try to reproduce the last exemple:

In [4]:
A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.array([[2], [4]])
C = np.dot(A, B)

In [8]:
print("A %s\n%s\n" %(A.shape, A))
print("B %s\n%s\n" %(B.shape, B))
print("C %s\n%s" %(C.shape, C))

A (3, 2)
[[1 2]
 [3 4]
 [5 6]]

B (2, 1)
[[2]
 [4]]

C (3, 1)
[[10]
 [22]
 [34]]


### Example 2.

Multiplication of two matrices.

$\boldsymbol{A} _{4,3} \times \boldsymbol{B} _{3, 2} = \boldsymbol{C} _{4, 2}$

$
\begin{bmatrix}
    A_{1,1} & A_{1,2} & A_{1,3} \\\\
    A_{2,1} & A_{2,2} & A_{2,3} \\\\
    A_{3,1} & A_{3,2} & A_{3,3} \\\\
    A_{4,1} & A_{4,2} & A_{4,3}
\end{bmatrix}\times
\begin{bmatrix}
    B_{1,1} & B_{1,2} \\\\
    B_{2,1} & B_{2,2} \\\\
    B_{3,1} & B_{3,2}
\end{bmatrix}=
\begin{bmatrix}
    A_{1,1} \times B_{1,1} + A_{1,2} \times B_{2,1} + A_{1,3} \times B_{3,1} & A_{1,1} \times B_{1,2} + A_{1,2} \times B_{2,2} + A_{1,3} \times B_{3,2} \\\\
    A_{2,1} \times B_{1,1} + A_{2,2} \times B_{2,1} + A_{2,3} \times B_{3,1} & A_{2,1} \times B_{1,2} + A_{2,2} \times B_{2,2} + A_{2,3} \times B_{3,2} \\\\
    A_{3,1} \times B_{1,1} + A_{3,2} \times B_{2,1} + A_{3,3} \times B_{3,1} & A_{3,1} \times B_{1,2} + A_{3,2} \times B_{2,2} + A_{3,3} \times B_{3,2} \\\\
    A_{4,1} \times B_{1,1} + A_{4,2} \times B_{2,1} + A_{4,3} \times B_{3,1} & A_{4,1} \times B_{1,2} + A_{4,2} \times B_{2,2} + A_{4,3} \times B_{3,2} \\\\
\end{bmatrix}
$

In [9]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
B = np.array([[2, 7], [1, 2], [3, 6]])
C = np.dot(A, B)

In [12]:
print("A.shape: %s\n%s\n" %(A.shape, A))
print("B.shape: %s\n%s\n" %(B.shape, B))
print("C.shape: %s\n%s" %(C.shape, C))

A.shape: (4, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

B.shape: (3, 2)
[[2 7]
 [1 2]
 [3 6]]

C.shape: (4, 2)
[[ 13  29]
 [ 31  74]
 [ 49 119]
 [ 67 164]]


#### So the dot product can be formalized like that:

$$
C_{i,j} = A_{i,k}B_{k,j} = \sum_{k}A_{i,k}B_{k,j}
$$

More detailed examples about the dot product can be found [here](https://www.mathsisfun.com/algebra/matrix-multiplying.html).

# Matrices mutliplication is distributive

$\boldsymbol{A}(\boldsymbol{B}+\boldsymbol{C}) = \boldsymbol{AB}+\boldsymbol{AC}$

### Example 3.

$
\boldsymbol{A}=\begin{bmatrix}
    2 & 3 \\\\
    1 & 4 \\\\
    7 & 6
\end{bmatrix}, 
\boldsymbol{B}=\begin{bmatrix}
    5 \\\\
    2
\end{bmatrix}, 
\boldsymbol{C}=\begin{bmatrix}
    4 \\\\
    3
\end{bmatrix}
$


$
\boldsymbol{A}(\boldsymbol{B}+\boldsymbol{C})=\begin{bmatrix}
    2 & 3 \\\\
    1 & 4 \\\\
    7 & 6
\end{bmatrix}\times
\left(\begin{bmatrix}
    5 \\\\
    2
\end{bmatrix}+
\begin{bmatrix}
    4 \\\\
    3
\end{bmatrix}\right)=
\begin{bmatrix}
    2 & 3 \\\\
    1 & 4 \\\\
    7 & 6
\end{bmatrix}\times
\begin{bmatrix}
    9 \\\\
    5
\end{bmatrix}=
\begin{bmatrix}
    2 \times 9 + 3 \times 5 \\\\
    1 \times 9 + 4 \times 5 \\\\
    7 \times 9 + 6 \times 5
\end{bmatrix}=
\begin{bmatrix}
    33 \\\\
    29 \\\\
    93
\end{bmatrix}
$

is equivalent to

$
\boldsymbol{A}\boldsymbol{B}+\boldsymbol{A}\boldsymbol{C} = \begin{bmatrix}
    2 & 3 \\\\
    1 & 4 \\\\
    7 & 6
\end{bmatrix}\times
\begin{bmatrix}
    5 \\\\
    2
\end{bmatrix}+
\begin{bmatrix}
    2 & 3 \\\\
    1 & 4 \\\\
    7 & 6
\end{bmatrix}\times
\begin{bmatrix}
    4 \\\\
    3
\end{bmatrix}=
\begin{bmatrix}
    2 \times 5 + 3 \times 2 \\\\
    1 \times 5 + 4 \times 2 \\\\
    7 \times 5 + 6 \times 2
\end{bmatrix}+
\begin{bmatrix}
    2 \times 4 + 3 \times 3 \\\\
    1 \times 4 + 4 \times 3 \\\\
    7 \times 4 + 6 \times 3
\end{bmatrix}=
\begin{bmatrix}
    16 \\\\
    13 \\\\
    47
\end{bmatrix}+
\begin{bmatrix}
    17 \\\\
    16 \\\\
    46
\end{bmatrix}=
\begin{bmatrix}
    33 \\\\
    29 \\\\
    93
\end{bmatrix}
$

In [10]:
A = np.array([[2, 3], [1, 4], [7, 6]])
print("A.shape: %s\n\n%s" %(A.shape, A))
B = np.array([[5], [2]])
print("\nB.shape: %s\n\n%s" %(B.shape, B))

A.shape: (3, 2)

[[2 3]
 [1 4]
 [7 6]]

B.shape: (2, 1)

[[5]
 [2]]


In [11]:
C = np.array([[4], [3]])
print("C.shape: %s\n\n%s" %(C.shape, C))

C.shape: (2, 1)

[[4]
 [3]]


In [12]:
# A(B + C)
D = np.dot(A, (B+C))
print("D.shape: %s\n\n%s" %(D.shape, D))

D.shape: (3, 1)

[[33]
 [29]
 [93]]


In [13]:
# AB + AC
D = np.dot(A, B) + np.dot(A, C)
print("D.shape: %s\n\n%s" %(D.shape, D))

D.shape: (3, 1)

[[33]
 [29]
 [93]]


# Matrices mutliplication is associative

$\boldsymbol{A}(\boldsymbol{BC}) = \boldsymbol{AB}(\boldsymbol{C})$


In [14]:
A = np.array([[2, 3], [1, 4], [7, 6]])
print("A.shape: %s\n\n%s" %(A.shape, A))
B = np.array([[5, 3], [2, 2]])
print("\nB.shape: %s\n\n%s" %(B.shape, B))

A.shape: (3, 2)

[[2 3]
 [1 4]
 [7 6]]

B.shape: (2, 2)

[[5 3]
 [2 2]]


In [15]:
# A(BC)
D = np.dot(A, np.dot(B, C))
print("D.shape: %s\n\n%s" %(D.shape, D))

D.shape: (3, 1)

[[100]
 [ 85]
 [287]]


In [16]:
# AB(C)
D = np.dot(np.dot(A, B), C)
print("D.shape: %s\n\n%s" %(D.shape, D))

D.shape: (3, 1)

[[100]
 [ 85]
 [287]]


# Matrix multiplication is not commutative

$\boldsymbol{AB} \neq \boldsymbol{BA}$

In [17]:
A = np.array([[2, 3], [6, 5]])
print("\nA.shape: %s\n\n%s" %(A.shape, A))

B = np.array([[5, 3], [2, 2]])
print("\nB.shape: %s\n\n%s" %(B.shape, B))


A.shape: (2, 2)

[[2 3]
 [6 5]]

B.shape: (2, 2)

[[5 3]
 [2 2]]


In [18]:
AB = np.dot(A, B)
print("AB.shape: %s\n\n%s" %(AB.shape, AB))

AB.shape: (2, 2)

[[16 12]
 [40 28]]


In [19]:
BA = np.dot(B, A)
print("BA.shape: %s\n\n%s" %(BA.shape, BA))

BA.shape: (2, 2)

[[28 30]
 [16 16]]


## However vector multiplication is commutative

$x^{ \text{T}}y = y^{\text{T}}x $

In [20]:
x = np.array([[2], [6]])
print("\nx.shape: %s\n\n%s" %(x.shape, x))

y = np.array([[5], [2]])
print("\ny.shape: %s\n\n%s" %(y.shape, y))


x.shape: (2, 1)

[[2]
 [6]]

y.shape: (2, 1)

[[5]
 [2]]


In [21]:
x_ty = np.dot(x.T, y)
print("x_ty.shape: %s\n\n%s" %(x_ty.shape, x_ty))

x_ty.shape: (1, 1)

[[22]]


In [22]:
y_tx = np.dot(y.T, x)
print("y_tx.shape: %s\n\n%s" %(y_tx.shape, y_tx))

y_tx.shape: (1, 1)

[[22]]


## Simplification of the matrix product

$(AB)^{\text{T}} = B^{\text{T}}A^{\text{T}}$

In [23]:
A = np.array([[2, 3], [1, 4], [7, 6]])
print("A.shape: %s\n\n%s" %(A.shape, A))
B = np.array([[5, 3], [2, 2]])
print("\nB.shape: %s\n\n%s" %(B.shape, B))

A.shape: (3, 2)

[[2 3]
 [1 4]
 [7 6]]

B.shape: (2, 2)

[[5 3]
 [2 2]]


$(AB)^{\text{T}}$:

In [24]:
AB_t = np.dot(A, B).T
print("AB_t.shape: %s\n\n%s" %(AB_t.shape, AB_t))

AB_t.shape: (2, 3)

[[16 13 47]
 [12 11 33]]


$B^{\text{T}}A^{\text{T}}$:

In [25]:
B_tA = np.dot(B.T, A.T)
print("B_tA.shape: %s\n\n%s" %(B_tA.shape, B_tA))

B_tA.shape: (2, 3)

[[16 13 47]
 [12 11 33]]


# System of linear equations

Matrices can be used to describe a system of linear equations of the form $\boldsymbol{Ax}=\boldsymbol{b}$. Here is a set of linear equations:

$$
A_{1,1}x_1 + A_{1,2}x_2 + A_{1,n}x_n = b_1 \\\\
A_{2,1}x_1 + A_{2,2}x_2 + A_{2,n}x_n = b_2 \\\\
\cdots \\\\
A_{m,1}x_1 + A_{m,2}x_2 + A_{m,n}x_n = b_n
$$

The left hand term can considered as the product of a matrix **A** containing weights for each variable ($n$ columns) and each equation ($m$ rows)

$$
\begin{bmatrix}
    A_{1,1} & A_{1,2} & \cdots & A_{1,n} \\\\
    A_{2,1} & A_{2,2} & \cdots & A_{2,n} \\\\
    \cdots & \cdots & \cdots & \cdots \\\\
    A_{m,1} & A_{m,2} & \cdots & A_{m,n}
\end{bmatrix}
$$

with a vector **x** containing the $n$ variables

$$
\begin{bmatrix}
    x_1 \\\\
    x_2 \\\\
    \cdots \\\\
    x_n
\end{bmatrix}
$$

The equation system can be wrote like that

$$
\begin{bmatrix}
    A_{1,1} & A_{1,2} & \cdots & A_{1,n} \\\\
    A_{2,1} & A_{2,2} & \cdots & A_{2,n} \\\\
    \cdots & \cdots & \cdots & \cdots \\\\
    A_{m,1} & A_{m,2} & \cdots & A_{m,n}
\end{bmatrix}
\times
\begin{bmatrix}
    x_1 \\\\
    x_2 \\\\
    \cdots \\\\
    x_n
\end{bmatrix}
=
\begin{bmatrix}
    b_1 \\\\
    b_2 \\\\
    \cdots \\\\
    b_m
\end{bmatrix}
$$

Or simply $\boldsymbol{Ax}=\boldsymbol{b}$.

### Example 4.

The common form of a linear equation ($y=ax+b$) can be converted to the matrix form. In this example, we'll use the variable name $w$ instead of $x$ to avoid confusion with our vector **x** that contain the variables.

$$
\begin{align*}
&y=2w+1\\\\
\Leftrightarrow& 2w-y=-1
\end{align*}
$$

In this example, the system of equations contains only 1 equation (1 row: $m=1$) and 2 variables (2 columns: $n=2$). It is the same thing as $A_{1,1}x_1 + A_{1,2}x_2 + A_{1,n}x_n = b_1$ with 

- $A_{1,1}$ is 2
- $x_1$ is the variable $w$
- $A_{1,2}$ is -1
- $x_2$ is the variable $y$
- $b$ is -1

This equation can be wrote under the matrix form. **A** will be the matrix of dimension $m\times n$ containing scalars multiplying these variables (here $w$ is multiplied by 2 and $y$ by -1). The vector **x** contains the variables $w$ and $y$. And the right hand term is the constant **b**:

$$
A=
\begin{bmatrix}
    2 & -1
\end{bmatrix}
$$

$$
x=
\begin{bmatrix}
    w\\\\
    y
\end{bmatrix}
$$

$$
b=
\begin{bmatrix}
    -1
\end{bmatrix}
$$

The matrix product between **A** and **x** gives us the right left hand side of the equation:

$$
\begin{align*}
Ax&=
\begin{bmatrix}
    2 & -1
\end{bmatrix}
\begin{bmatrix}
    y\\\\
    z
\end{bmatrix}\\\\
&=
2w - y\\\\
b &= -1\\\\
\Leftrightarrow
&2w - y = -1
\end{align*}
$$