In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Plot parameters
plt.style.use('ggplot')
plt.rcParams['axes.facecolor']='w'

%pylab inline
pylab.rcParams['figure.figsize'] = (3, 3)

Populating the interactive namespace from numpy and matplotlib


In [3]:
# Avoid inaccurate floating values (for inverse matrices in dot product for instance)
# See https://stackoverflow.com/questions/24537791/numpy-matrix-inversion-rounding-errors
np.set_printoptions(suppress=True)

# 2.2 Multiplying Matrices and Vectors

The standard way to multiply matrices is not to multiply each element of one with each elements of the other (this is the element-wise product). The matrix product, also called **dot product**, is calculated as following:

<img src="images/dotProduct.png" width="400" alt="dotProduct">

This implies that the number of columns of the first matrix must be equals to the number of rows of the second matrix. Thus, if the shape of the first matrix is ($m \times n$) the second matrix need to be of shape ($n \times x$).

### Example 1.

Multiplication of a matrix and a vector.

$$\boldsymbol{A} _{3,2} \times \boldsymbol{B} _{2, 1} = \boldsymbol{C} _{3, 1}$$

$$
\begin{align*}
&\begin{bmatrix}
    A_{1,1} & A_{1,2} \\\\
    A_{2,1} & A_{2,2} \\\\
    A_{3,1} & A_{3,2}
\end{bmatrix}\times
\begin{bmatrix}
    B_{1,1} \\\\
    B_{2,1}
\end{bmatrix}=\\\\
&\begin{bmatrix}
    A_{1,1}B_{1,1} + A_{1,2}B_{2,1} \\\\
    A_{2,1}B_{1,1} + A_{2,2}B_{2,1} \\\\
    A_{3,1}B_{1,1} + A_{3,2}B_{2,1}
\end{bmatrix}
\end{align*}
$$

For instance

$$
\begin{align*}
&\begin{bmatrix}
    1 & 2 \\\\
    3 & 4 \\\\
    5 & 6
\end{bmatrix}\times
\begin{bmatrix}
    2 \\\\
    4
\end{bmatrix}=\\\\
&\begin{bmatrix}
    1 \times 2 + 2 \times 4 \\\\
    3 \times 2 + 4 \times 4 \\\\
    5 \times 2 + 6 \times 4
\end{bmatrix}=
\begin{bmatrix}
    10 \\\\
    22 \\\\
    34
\end{bmatrix}
\end{align*}
$$

#### The Numpy command 'dot' can be used to compute the matrix product (or dot product)

Let's try to reproduce the last exemple:

In [28]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
B = np.array([[2], [4]])
B

array([[2],
       [4]])

In [30]:
C = np.dot(A, B)
C

array([[10],
       [22],
       [34]])

It is even easier to use the method `dot()` of Numpy arrays:

In [27]:
C = A.dot(B)
C

array([[10],
       [22],
       [34]])

### Example 2.

Multiplication of two matrices.

$$\boldsymbol{A} _{4,3} \times \boldsymbol{B} _{3, 2} = \boldsymbol{C} _{4, 2}$$

$$
\begin{align*}
&\begin{bmatrix}
    A_{1,1} & A_{1,2} \\\\
    A_{2,1} & A_{2,2} \\\\
    A_{3,1} & A_{3,2} \\\\
    A_{4,1} & A_{4,2}
\end{bmatrix}\times
\begin{bmatrix}
    B_{1,1} & B_{1,2} \\\\
    B_{2,1} & B_{2,2}
\end{bmatrix}=\\\\
&\begin{bmatrix}
    A_{1,1}B_{1,1} + A_{1,2}B_{2,1} & A_{1,1}B_{1,2} + A_{1,2}B_{2,2} \\\\
    A_{2,1}B_{1,1} + A_{2,2}B_{2,1} & A_{2,1}B_{1,2} + A_{2,2}B_{2,2} \\\\
    A_{3,1}B_{1,1} + A_{3,2}B_{2,1} & A_{3,1}B_{1,2} + A_{3,2}B_{2,2} \\\\
    A_{4,1}B_{1,1} + A_{4,2}B_{2,1} & A_{4,1}B_{1,2} + A_{4,2}B_{2,2}
\end{bmatrix}
\end{align*}
$$

For instance

$$
\begin{align*}
&\begin{bmatrix}
    1 & 2 & 3 \\\\
    4 & 5 & 6 \\\\
    7 & 8 & 9 \\\\
    10 & 11 & 12
\end{bmatrix}\times
\begin{bmatrix}
    2 & 7 \\\\
    1 & 2 \\\\
    3 & 6
\end{bmatrix}=\\\\
&\begin{bmatrix}
    2 \times 1 + 1 \times 2 + 3 \times 3 & 7 \times 1 + 2 \times 2 + 6 \times 3 \\\\
    2 \times 4 + 1 \times 5 + 3 \times 6 & 7 \times 4 + 2 \times 5 + 6 \times 6 \\\\
    2 \times 7 + 1 \times 8 + 3 \times 9 & 7 \times 7 + 2 \times 8 + 6 \times 9 \\\\
    2 \times 10 + 1 \times 11 + 3 \times 12 & 7 \times 10 + 2 \times 11 + 6 \times 12 \\\\
\end{bmatrix}\\\\
&=
\begin{bmatrix}
    13 & 29 \\\\
    31 & 74 \\\\
    49 & 119 \\\\
    67 & 164
\end{bmatrix}
\end{align*}
$$

In [31]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [32]:
B = np.array([[2, 7], [1, 2], [3, 6]])
B

array([[2, 7],
       [1, 2],
       [3, 6]])

In [33]:
C = np.dot(A, B)
C

array([[ 13,  29],
       [ 31,  74],
       [ 49, 119],
       [ 67, 164]])

It works!

#### So the dot product can be formalized like that:

$$
C_{i,j} = A_{i,k}B_{k,j} = \sum_{k}A_{i,k}B_{k,j}
$$

More detailed examples about the dot product can be found [here](https://www.mathsisfun.com/algebra/matrix-multiplying.html).

# Matrices mutliplication is distributive

$$\boldsymbol{A}(\boldsymbol{B}+\boldsymbol{C}) = \boldsymbol{AB}+\boldsymbol{AC}$$

### Example 3.

$$
\boldsymbol{A}=\begin{bmatrix}
    2 & 3 \\\\
    1 & 4 \\\\
    7 & 6
\end{bmatrix}, 
\boldsymbol{B}=\begin{bmatrix}
    5 \\\\
    2
\end{bmatrix}, 
\boldsymbol{C}=\begin{bmatrix}
    4 \\\\
    3
\end{bmatrix}
$$


$$
\begin{align*}
\boldsymbol{A}(\boldsymbol{B}+\boldsymbol{C})&=\begin{bmatrix}
    2 & 3 \\\\
    1 & 4 \\\\
    7 & 6
\end{bmatrix}\times
\left(\begin{bmatrix}
    5 \\\\
    2
\end{bmatrix}+
\begin{bmatrix}
    4 \\\\
    3
\end{bmatrix}\right)=
\begin{bmatrix}
    2 & 3 \\\\
    1 & 4 \\\\
    7 & 6
\end{bmatrix}\times
\begin{bmatrix}
    9 \\\\
    5
\end{bmatrix}\\\\
&=
\begin{bmatrix}
    2 \times 9 + 3 \times 5 \\\\
    1 \times 9 + 4 \times 5 \\\\
    7 \times 9 + 6 \times 5
\end{bmatrix}=
\begin{bmatrix}
    33 \\\\
    29 \\\\
    93
\end{bmatrix}
\end{align*}
$$

is equivalent to

$$
\begin{align*}
\boldsymbol{A}\boldsymbol{B}+\boldsymbol{A}\boldsymbol{C} &= \begin{bmatrix}
    2 & 3 \\\\
    1 & 4 \\\\
    7 & 6
\end{bmatrix}\times
\begin{bmatrix}
    5 \\\\
    2
\end{bmatrix}+
\begin{bmatrix}
    2 & 3 \\\\
    1 & 4 \\\\
    7 & 6
\end{bmatrix}\times
\begin{bmatrix}
    4 \\\\
    3
\end{bmatrix}\\\\
&=
\begin{bmatrix}
    2 \times 5 + 3 \times 2 \\\\
    1 \times 5 + 4 \times 2 \\\\
    7 \times 5 + 6 \times 2
\end{bmatrix}+
\begin{bmatrix}
    2 \times 4 + 3 \times 3 \\\\
    1 \times 4 + 4 \times 3 \\\\
    7 \times 4 + 6 \times 3
\end{bmatrix}\\\\
&=
\begin{bmatrix}
    16 \\\\
    13 \\\\
    47
\end{bmatrix}+
\begin{bmatrix}
    17 \\\\
    16 \\\\
    46
\end{bmatrix}=
\begin{bmatrix}
    33 \\\\
    29 \\\\
    93
\end{bmatrix}
\end{align*}
$$

In [35]:
A = np.array([[2, 3], [1, 4], [7, 6]])
A

array([[2, 3],
       [1, 4],
       [7, 6]])

In [36]:
B = np.array([[5], [2]])
B

array([[5],
       [2]])

In [37]:
C = np.array([[4], [3]])
C

array([[4],
       [3]])

$\boldsymbol{A}(\boldsymbol{B}+\boldsymbol{C})$:

In [39]:
D = np.dot(A, (B+C))
D

array([[33],
       [29],
       [93]])

is equivalent to

$\boldsymbol{AB}+\boldsymbol{AC}$:

In [40]:
D = np.dot(A, B) + np.dot(A, C)
D

array([[33],
       [29],
       [93]])

# Matrices mutliplication is associative

$$\boldsymbol{A}(\boldsymbol{BC}) = \boldsymbol{AB}(\boldsymbol{C})$$


In [44]:
A = np.array([[2, 3], [1, 4], [7, 6]])
A

array([[2, 3],
       [1, 4],
       [7, 6]])

In [45]:
B = np.array([[5, 3], [2, 2]])
B

array([[5, 3],
       [2, 2]])

$\boldsymbol{A}(\boldsymbol{BC})$:


In [48]:
D = A.dot(B.dot(C))
D

array([[100],
       [ 85],
       [287]])

$\boldsymbol{AB}(\boldsymbol{C})$:

In [49]:
D = (A.dot(B)).dot(C)
D

array([[100],
       [ 85],
       [287]])

# Matrix multiplication is not commutative

$$\boldsymbol{AB} \neq \boldsymbol{BA}$$

In [50]:
A = np.array([[2, 3], [6, 5]])
A

array([[2, 3],
       [6, 5]])

In [51]:
B = np.array([[5, 3], [2, 2]])
B

array([[5, 3],
       [2, 2]])

$\boldsymbol{AB}$:

In [52]:
AB = np.dot(A, B)
AB

array([[16, 12],
       [40, 28]])

$\boldsymbol{BA}$:

In [53]:
BA = np.dot(B, A)
BA

array([[28, 30],
       [16, 16]])

## However vector multiplication is commutative

$$\boldsymbol{x^{ \text{T}}y} = \boldsymbol{y^{\text{T}}x} $$

In [54]:
x = np.array([[2], [6]])
x

array([[2],
       [6]])

In [55]:
y = np.array([[5], [2]])
y

array([[5],
       [2]])

$\boldsymbol{x^\text{T}y}$:

In [62]:
x_ty = np.dot(x.T, y)
x_ty

array([[22]])

$\boldsymbol{y^\text{T}x}$:

In [57]:
y_tx = np.dot(y.T, x)
y_tx

array([[22]])

## Simplification of the matrix product

$$(\boldsymbol{AB})^{\text{T}} = \boldsymbol{B^{\text{T}}A}^{\text{T}}$$

In [58]:
A = np.array([[2, 3], [1, 4], [7, 6]])
A

array([[2, 3],
       [1, 4],
       [7, 6]])

In [59]:
B = np.array([[5, 3], [2, 2]])
B

array([[5, 3],
       [2, 2]])

$(\boldsymbol{AB})^{\text{T}}$:

In [60]:
AB_t = np.dot(A, B).T
AB_t

array([[16, 13, 47],
       [12, 11, 33]])

$\boldsymbol{B^{\text{T}}A}^{\text{T}}$:

In [61]:
B_tA = np.dot(B.T, A.T)
B_tA

array([[16, 13, 47],
       [12, 11, 33]])

# System of linear equations

Matrices can be used to describe a system of linear equations of the form $\boldsymbol{Ax}=\boldsymbol{b}$. Here is a set of linear equations:

$$
A_{1,1}x_1 + A_{1,2}x_2 + A_{1,n}x_n = b_1 \\\\
A_{2,1}x_1 + A_{2,2}x_2 + A_{2,n}x_n = b_2 \\\\
\cdots \\\\
A_{m,1}x_1 + A_{m,2}x_2 + A_{m,n}x_n = b_n
$$

The left hand term can considered as the product of a matrix $\boldsymbol{A}$ containing weights for each variable ($n$ columns) and each equation ($m$ rows):

$$
\boldsymbol{A}=
\begin{bmatrix}
    A_{1,1} & A_{1,2} & \cdots & A_{1,n} \\\\
    A_{2,1} & A_{2,2} & \cdots & A_{2,n} \\\\
    \cdots & \cdots & \cdots & \cdots \\\\
    A_{m,1} & A_{m,2} & \cdots & A_{m,n}
\end{bmatrix}
$$

with a vector $\boldsymbol{x}$ containing the $n$ unknowns

$$
\boldsymbol{x}=
\begin{bmatrix}
    x_1 \\\\
    x_2 \\\\
    \cdots \\\\
    x_n
\end{bmatrix}
$$

The dot product of $\boldsymbol{A}$ and $\boldsymbol{x}$ gives a set of equations. Here is a simple example:

<img src="images/equationSystem.png" width="400" alt="equationSystem">

We have well a set of two equations with two unknowns. So the number of rows of $\boldsymbol{A}$ gives the number of equations and the number of columns gives the number of unknowns.

The equation system can be wrote like that:

$$
\begin{bmatrix}
    A_{1,1} & A_{1,2} & \cdots & A_{1,n} \\\\
    A_{2,1} & A_{2,2} & \cdots & A_{2,n} \\\\
    \cdots & \cdots & \cdots & \cdots \\\\
    A_{m,1} & A_{m,2} & \cdots & A_{m,n}
\end{bmatrix}
\times
\begin{bmatrix}
    x_1 \\\\
    x_2 \\\\
    \cdots \\\\
    x_n
\end{bmatrix}
=
\begin{bmatrix}
    b_1 \\\\
    b_2 \\\\
    \cdots \\\\
    b_m
\end{bmatrix}
$$

Or simply:

$$\boldsymbol{Ax}=\boldsymbol{b}$$


### Example 4.

We will try to convert the common form of a linear equation:

$$y=ax+b$$

to the matrix form. If we want to keep the previous notation:

$$x_2=ax_1+b$$

Don't confuse the variable $x_1$ and $x_2$ with the vector $\boldsymbol{x}$. This vector contains actually all the variables of our equations. Here we have:

$$
\boldsymbol{x} =
\begin{bmatrix}
    x_1 \\
    x_2
\end{bmatrix}
$$

In this example we will use the following equation:

$$
\begin{align*}
&x_2=2x_1+1\\\\
\Leftrightarrow& 2x_1-x_2=-1
\end{align*}
$$

If we want to end up with this system when we multiply $\boldsymbol{A}$ and $\boldsymbol{x}$ we need $\boldsymbol{A}$ to be:

$$
\boldsymbol{A}=
\begin{bmatrix}
    2 & -1
\end{bmatrix}
$$

because

$$
\begin{bmatrix}
    2 & -1
\end{bmatrix}
\cdot
\begin{bmatrix}
    x_1 \\
    x_2
\end{bmatrix}
=
\begin{bmatrix}
2x_1-1x_2
\end{bmatrix}
$$

To complete the equation we have

$$
\boldsymbol{b}=
\begin{bmatrix}
    -1
\end{bmatrix}
$$

which gives

$$
\begin{bmatrix}
    2 & -1
\end{bmatrix}
\cdot
\begin{bmatrix}
    x_1 \\
    x_2
\end{bmatrix}
=
\begin{bmatrix}
    -1
\end{bmatrix}
$$

This system of equations is thus very simple and contains only 1 equation ($\boldsymbol{A}$ has 1 row) and 2 variables ($\boldsymbol{A}$ has 2 columns). 

To summarise $\boldsymbol{A}$ will be the matrix of dimensions $m\times n$ containing scalars multiplying these variables (here $x_1$ is multiplied by 2 and $x_2$ by -1). The vector $\boldsymbol{x}$ contains the variables $x_1$ and $x_2$. And the right hand term is the constant $\boldsymbol{b}$:

$$
\boldsymbol{A}=
\begin{bmatrix}
    2 & -1
\end{bmatrix}
$$

$$
\boldsymbol{x}=
\begin{bmatrix}
    x_1\\\\
    x_2
\end{bmatrix}
$$

$$
\boldsymbol{b}=
\begin{bmatrix}
    -1
\end{bmatrix}
$$

We can write this system

$$
\boldsymbol{Ax}=\boldsymbol{b}
$$

We will see in [the next chapter]() that this compact way of writing set of linear equations can be very usefull. It provide actually a way to solve the equations.

# References

[1] [Math is fun - Multiplying matrices](https://www.mathsisfun.com/algebra/matrix-multiplying.html)