In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# Plot parameters
plt.style.use('ggplot')
plt.rcParams['axes.facecolor']='w'

%pylab inline
pylab.rcParams['figure.figsize'] = (3, 3)

Populating the interactive namespace from numpy and matplotlib


In [4]:
# Avoid inaccurate floating values (for inverse matrices in dot product for instance)
# See https://stackoverflow.com/questions/24537791/numpy-matrix-inversion-rounding-errors
np.set_printoptions(suppress=True)

# 2.1 Scalars, Vectors, Matrices and Tensors

![scalar-matrix](images/scalar-tensor.png)

- A scalar is a single number
- A vector is an array of numbers.

$
\boldsymbol{x} =\begin{bmatrix}
    x_1 \\\\
    x_2 \\\\
    \cdots \\\\
    x_n
\end{bmatrix}
$

- A matrix is a 2-D array

$
\boldsymbol{A}=
\begin{bmatrix}
    A_{1,1} & A_{1,2} & \cdots & A_{1,n} \\\\
    A_{2,1} & A_{2,2} & \cdots & A_{2,n} \\\\
    \cdots & \cdots & \cdots & \cdots \\\\
    A_{m,1} & A_{m,2} & \cdots & A_{m,n}
\end{bmatrix}
$

- A tensor is a $n$-D array with $n>2$

### Example 1.

#### Create a vector with Python and Numpy

In [5]:
x = np.array([1, 2, 3, 4])
print(x)

[1 2 3 4]


### Example 2.

#### Create a (3x2) matrix (nested brackets)

In [6]:
A = np.array([[1, 2], [3, 4], [5, 6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


### Shape

The shape of an array gives you the dimensions of the array. For a 2-D array it will give you the number of rows and the number of columns. Let's find the shape of our preceding 2-D array `A`. Since `A` is a Numpy array (it was created with the command `np.array`) you can access its shape with:

In [7]:
A.shape

(3, 2)

We can see that $\boldsymbol{A}$ has indeed 3 rows and 2 columns.

# Transpose

The transposition of a vector go from the column form to the row form:

![transposeVector](images/transposeVector.png)

The transpose $A^{\text{T}}$ of the matrix A corresponds to the mirrored axes. If the matrix is a square matrix (same number of columns and rows):

![transposeMatrixSquare](images/transposeMatrixSquare.png)

If the matrix is not square the idea is the same:

![transposeMatrix](images/transposeMatrix.png)

The superscript $^T$ is used for transposed matrices.

$
\boldsymbol{A}=
\begin{bmatrix}
    A_{1,1} & A_{1,2} \\\\
    A_{2,1} & A_{2,2} \\\\
    A_{3,1} & A_{3,2}
\end{bmatrix}
$

$
\boldsymbol{A}^{\text{T}}=
\begin{bmatrix}
    A_{1,1} & A_{2,1} & A_{3,1} \\\\
    A_{1,2} & A_{2,2} & A_{3,2}
\end{bmatrix}
$

The shape ($m \times n$) is inverted and becomes ($n \times m$).

![transposeMatrixDim](images/transposeMatrixDim.png)


### Example 3.

#### Create a matrix A and transpose it

In [8]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A_t = A.T

We can check the result of the transposition and the dimensions of the matrices:

In [13]:
print("A.shape: %s\n%s" %(A.shape, A))
print("\nA_t.shape: %s\n%s\n" %(A_t.shape, A_t))

A.shape: (3, 2)
[[1 2]
 [3 4]
 [5 6]]

A_t.shape: (2, 3)
[[1 3 5]
 [2 4 6]]



We can see that the number of columns becomes the number of rows with transposition and vice versa.

# Addition

![additionMatrix](images/additionMatrix.png)

Matrices can be added if they have the same shape:

$\boldsymbol{A} + \boldsymbol{B} = \boldsymbol{C}$

with each cell of $\boldsymbol{A}$ is added to the corresponding cell of $\boldsymbol{B}$:

$\boldsymbol{A}_{i,j} + \boldsymbol{B}_{i,j} = \boldsymbol{C}_{i,j}$

$i$ is the row index and $j$ the column index.

$
\begin{bmatrix}
    A_{1,1} & A_{1,2} \\\\
    A_{2,1} & A_{2,2} \\\\
    A_{3,1} & A_{3,2}
\end{bmatrix}+
\begin{bmatrix}
    B_{1,1} & B_{1,2} \\\\
    B_{2,1} & B_{2,2} \\\\
    B_{3,1} & B_{3,2}
\end{bmatrix}=
\begin{bmatrix}
    A_{1,1} + B_{1,1} & A_{1,2} + B_{1,2} \\\\
    A_{2,1} + B_{2,1} & A_{2,2} + B_{2,2} \\\\
    A_{3,1} + B_{3,1} & A_{3,2} + B_{3,2}
\end{bmatrix}
$

The shape of $\boldsymbol{A}$, $\boldsymbol{B}$ and $\boldsymbol{C}$ are identical. Let's check that:

### Example 4.

#### Create two matrices A and B and add them

With Numpy you can add matrices just as you would add vectors or scalars.

In [14]:
A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.array([[2, 5], [7, 4], [4, 3]])
# Add matrices A and B
C = A + B

In [35]:
print("A \n%s\n" %A)
print("B \n%s\n" %B)
print("C \n%s" %C)

A 
[[1 2]
 [3 4]
 [5 6]]

B 
[[2]
 [4]
 [6]]

C 
[[ 3  4]
 [ 7  8]
 [11 12]]


It is also possible to add a scalar to a matrix. This means adding this scalar to each cell of the matrix.

$
\alpha+ \begin{bmatrix}
    A_{1,1} & A_{1,2} \\\\
    A_{2,1} & A_{2,2} \\\\
    A_{3,1} & A_{3,2}
\end{bmatrix}=
\begin{bmatrix}
    \alpha + A_{1,1} & \alpha + A_{1,2} \\\\
    \alpha + A_{2,1} & \alpha + A_{2,2} \\\\
    \alpha + A_{3,1} & \alpha + A_{3,2}
\end{bmatrix}
$

### Example 5.

#### Add a scalar to a matrix

It is also possible to add a scalar to a matrix. In that case, the scalar will be added to each element of the matrix.

In [25]:
# Exemple: Add 4 to the matrix A
C = A+4

In [34]:
print("A \n%s\n" %A)
print("C \n%s" %C)

A 
[[1 2]
 [3 4]
 [5 6]]

C 
[[ 3  4]
 [ 7  8]
 [11 12]]


# Broadcasting

Numpy can handle operations on arrays of different shapes. The smaller array will be extended to match the shape of the bigger one. The advantage is that this is done in `C` under the hood (like any vectorized operation in Numpy). Actually the simpler example of broadcasting is what we saw before when multiplied a scalar with a matrix. The scalar was converted in an array of same shape as $\boldsymbol{A}$.

Here is another generic example:

$
\begin{bmatrix}
    A_{1,1} & A_{1,2} \\\\
    A_{2,1} & A_{2,2} \\\\
    A_{3,1} & A_{3,2}
\end{bmatrix}+
\begin{bmatrix}
    B_{1,1} \\\\
    B_{2,1} \\\\
    B_{3,1}
\end{bmatrix}
$

is equivalent to

$
\begin{bmatrix}
    A_{1,1} & A_{1,2} \\\\
    A_{2,1} & A_{2,2} \\\\
    A_{3,1} & A_{3,2}
\end{bmatrix}+
\begin{bmatrix}
    B_{1,1} & B_{1,1} \\\\
    B_{2,1} & B_{2,1} \\\\
    B_{3,1} & B_{3,1}
\end{bmatrix}=
\begin{bmatrix}
    A_{1,1} + B_{1,1} & A_{1,2} + B_{1,1} \\\\
    A_{2,1} + B_{2,1} & A_{2,2} + B_{2,1} \\\\
    A_{3,1} + B_{3,1} & A_{3,2} + B_{3,1}
\end{bmatrix}
$

where the ($3 \times 1$) matrix is converted to the right shape ($3 \times 2$) by copying the first column. Numpy will do that automatically if the shapes can match.

### Example 6.

#### Add two matrices of different shapes

In [27]:
A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.array([[2], [4], [6]])
# Broadcasting
C=A+B

In [33]:
print("C \n%s\n" %C)
print("A \n%s\n" %A)
print("B \n%s\n" %B)

C 
[[ 3  4]
 [ 7  8]
 [11 12]]

A 
[[1 2]
 [3 4]
 [5 6]]

B 
[[2]
 [4]
 [6]]



# References

[1] [Broadcasting in Numpy](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html)